<!-- Multi-Select Options for Industry -->

<option value="Accounting"> Accounting  </option>
<option value="Advertising/Publication"> Advertising / Publication  </option>
<option value="Agriculture"> Agriculture </option>
<option value="Angel Funding"> Angel Funding </option>
<option value="Apparel/Accessories"> Apparel / Accessories </option>
<option value="Architecture/Design"> Architecture / Design </option>
<option value="Arts, Entertainment/Recreation"> Arts / Entertainment / Recreation </option>
<option value="Automotive"> Automotive </option>
<option value="Biotechnology/Health/Medical"> Biotechnology / Health / Medical </option>
<option value="Communication Services"> Communication Services </option>
<option value="Computer/Software"> Computer / Software </option>
<option value="E-commerce"> E-commerce </option>
<option value="Energy"> Energy </option>
<option value="Education/Training"> Education / Training </option>
<option value="Environmental"> Environmental </option>
<option value="Financial Services"> Financial Services </option>
<option value="Food/Beverage"> Food/Beverage </option>
<option value="Health Care/Biotech"> Health Care / Biotech </option>
<option value="Manufacturing"> Manufacturing </option>
<option value="Marketing/PR"> Marketing / PR </option>
<option value="Media Services"> Media Services </option>
<option value="Mining Industry"> Mining Industry </option>
<option value="Multimedia/Internet/Online services"> Multimedia / Internet / Online Services </option>
<option value="Office Equipment"> Office Equipment </option>
<option value="Oil/Gas"> Oil / Gas </option>
<option value="Plumbing"> Plumbing </option>
<option value="Printing/Graphics"> Printing / Graphics </option>
<option value="Product Licensing"> Product Licensing </option>
<option value="Real Estate"> Real Estate </option>
<option value="Retail or eCommerce"> Retail or eCommerce </option>
<option value="SaaS"> SaaS </option>
<option value="Social Entrepreneurship"> Social Entrepreneurship </option>
<option value="Sports/Fitness Services"> Sports / Fitness Services </option>
<option value="Television/Film"> Television / Film </option>
<option value="Travel/Transportation">Travel / Transportation </option>
<option value="Venture Capital or Private Equity"> Venture Capital or Private Equity </option>
<option value="Other"> Other </option>
