package org.ideavillage.mentormarketplace.persistence.domain;

import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Domain model representing an Founder. Closely resembles the database table. File was generated by NetBeans "New
 * -> Entity Classes from Database..." From the generated file, I had to change the id type from Integer to Long for the
 * repository to work. I think the reason for that is that PostgreSQL uses Longs for the serial type while other
 * databases might not. I also camelCased the linkedInId property to make it easier to read.
 *
 * @author 212395189
 */
@Entity
@Table(name = "founder")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Founder.findAll", query = "SELECT e FROM Founder e")})
public class Founder implements Serializable {

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Long id;
    @Size(max = 2147483647)
    @Column(name = "linkedinid")
    private String linkedInId;
    @Size(max = 2147483647)
    @Column(name = "industry")
    private String industry;

    public Founder() {
    }

    public Founder(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getLinkedInId() {
        return linkedInId;
    }

    public void setLinkedInId(String linkedInId) {
        this.linkedInId = linkedInId;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Founder)) {
            return false;
        }
        Founder other = (Founder) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }
    
    @Override
    public String toString() {
        return "org.ideavillage.mentormarketplace.persistence.domain.Founder[ id=" + id + " ]";
    }

}
