package org.ideavillage.mentormarketplace.persistence.domain;

import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import java.io.Serializable;
import javax.persistence.Basic;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.Table;
import javax.validation.constraints.Size;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Domain model representing an Founder. Closely resembles the database table. File was generated by NetBeans "New
 * -> Entity Classes from Database..." From the generated file, I had to change the id type from Integer to Long for the
 * repository to work. I think the reason for that is that PostgreSQL uses Longs for the serial type while other
 * databases might not. I also camelCased the linkedInId property to make it easier to read.
 *
 * @author 212395189
 */
@Entity
@Table(name = "founder")
@XmlRootElement
@NamedQueries({
    @NamedQuery(name = "Founder.findAll", query = "SELECT e FROM Founder e")})
public class Founder implements Serializable {
    
    @JoinColumn(name = "mmuser", referencedColumnName = "id")
    @ManyToOne(optional = false, fetch = FetchType.EAGER)
    private MMUser mmuser;

    private static final long serialVersionUID = 1L;
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Basic(optional = false)
    @Column(name = "id")
    private Long id;
    
    @Size(max = 2147483647)
    @Column(name = "firstname")
    private String firstName;
    
    @Size(max = 2147483647)
    @Column(name = "lastname")
    private String lastName;
    
    @Size(max = 2147483647)
    @Column(name = "industry")
    private String industry;
    
    @Size(max = 2147483647)
    @Column(name = "areasofexpertise")
    private String areasOfExpertise;
    
    @Size(max = 2147483647)
    @Column(name = "background")
    private String background;
    
    @Size(max = 2147483647)
    @Column(name = "website")
    private String website;
    
    @Size(max = 2147483647)
    @Column(name = "facebook")
    private String facebook;
    
    @Size(max = 2147483647)
    @Column(name = "twitter")
    private String twitter;
    
    @Size(max = 2147483647)
    @Column(name = "othersocialmedia")
    private String otherSocialMedia;
    
    @Size(max = 2147483647)
    @Column(name = "linkedinid")
    private String linkedInId;
     
    @Size(max = 2147483647)
    @Column(name = "linkedinpictureurl")
    private String linkedInPictureURL;
    
    @Size(max = 2147483647)
    @Column(name = "linkedincurrentcompany")
    private String linkedInCurrentCompany;
    
    @Size(max = 2147483647)
    @Column(name = "linkedincurrentjobtitle")
    private String linkedInCurrentJobTitle;
    
    @Size(max = 2147483647)
    @Column(name = "logo")
    private String logo;
    
    @Size(max = 2147483647)
    @Column(name = "tagline")
    private String tagline;
    
    @Size(max = 2147483647)
    @Column(name = "elevatorPitch")
    private String elevatorPitch;
    
    @Size(max = 2147483647)
    @Column(name = "immediateNeeds")
    private String immediateNeeds;
    
    @Size(max = 2147483647)
    @Column(name = "companyDetails")
    private String companyDetails;
    
    @Size(max = 2147483647)
    @Column(name = "inspiration")
    private String inspiration;
    
    @Size(max = 2147483647)
    @Column(name = "status")
    private String status;
    
    @Size(max = 2147483647)
    @Column(name = "vision")
    private String vision;
    
    @Size(max = 2147483647)
    @Column(name = "newOrleans")
    private String newOrleans;
    
    @Size(max = 2147483647)
    @Column(name = "programPlan")
    private String programPlan;
    
    @Size(max = 2147483647)
    @Column(name = "weeklyReports")
    private String weeklyReports;
    
    public Founder() {
    }

    public Founder(Long id) {
        this.id = id;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public String getFirstName() {
        return firstName;
    }
    
    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }
    
    public String getLastName() {
        return lastName;
    }
    
    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }
    
    public String getAreasOfExpertise() {
        return areasOfExpertise;
    }

    public void setAreasOfExpertise(String areasOfExpertise) {
        this.areasOfExpertise = areasOfExpertise;
    }
    
    public String getBackground() {
        return background;
    }

    public void setBackground(String background) {
        this.background = background;
    }
    
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }
    
    public String getFacebook() {
        return facebook;
    }

    public void setFacebook(String facebook) {
        this.facebook = facebook;
    }
    
    public String getTwitter() {
        return twitter;
    }

    public void setTwitter(String twitter) {
        this.twitter = twitter;
    }
    
    public String getOtherSocialMedia() {
        return otherSocialMedia;
    }

    public void setOtherSocialMedia(String otherSocialMedia) {
        this.otherSocialMedia = otherSocialMedia;
    }
    
    public String getLinkedInId() {
        return linkedInId;
    }

    public void setLinkedInId(String linkedInId) {
        this.linkedInId = linkedInId;
    }
    
    public String getLinkedInPictureURL() {
        return linkedInPictureURL;
    }

    public void setLinkedInPictureURL(String linkedInPictureURL) {
        this.linkedInPictureURL = linkedInPictureURL;
    }
    
    public String getLinkedInCurrentCompany() {
        return linkedInCurrentCompany;
    }

    public void setLinkedInCurrentCompany(String linkedInCurrentCompany) {
        this.linkedInCurrentCompany = linkedInCurrentCompany;
    }
    
    public String getLinkedInCurrentJobTitle() {
        return linkedInCurrentJobTitle;
    }

    public void setLinkedInCurrentJobTitle(String linkedInCurrentJobTitle) {
        this.linkedInCurrentJobTitle = linkedInCurrentJobTitle;
    }
    
    public String getLogo() {
        return logo;
    }

    public void setLogo(String logo) {
        this.logo = logo;
    }
    
    public String getTagline() {
        return tagline;
    }

    public void setTagline(String tagline) {
        this.tagline = tagline;
    }
    
    public String getElevatorPitch() {
        return elevatorPitch;
    }

    public void setElevatorPitch(String elevatorPitch) {
        this.elevatorPitch = elevatorPitch;
    }
    
    public String getImmediateNeeds() {
        return immediateNeeds;
    }

    public void setImmediateNeeds(String immediateNeeds) {
        this.immediateNeeds = immediateNeeds;
    }
    
    public String getCompanyDetails() {
        return companyDetails;
    }

    public void setCompanyDetails(String companyDetails) {
        this.companyDetails = companyDetails;
    }
    
    public String getInspiration() {
        return inspiration;
    }

    public void setInspiration(String inspiration) {
        this.inspiration = inspiration;
    }
    
    public String getStatus() {
        return status;
    }

    public void setStatus(String status) {
        this.status = status;
    }
    public String getVision() {
        return vision;
    }

    public void setVision(String vision) {
        this.vision = vision;
    }
    
    public String getNewOrleans() {
        return newOrleans;
    }

    public void setNewOrleans(String newOrleans) {
        this.newOrleans = newOrleans;
    }
    
    public String getProgramPlan() {
        return programPlan;
    }

    public void setProgramPlan(String programPlan) {
        this.programPlan = programPlan;
    }
    
    public String getWeeklyReports() {
        return weeklyReports;
    }

    public void setWeeklyReports(String weeklyReports) {
        this.weeklyReports = weeklyReports;
    }
    
    @Override
    public int hashCode() {
        int hash = 0;
        hash += (id != null ? id.hashCode() : 0);
        return hash;
    }

    @Override
    public boolean equals(Object object) {
        // TODO: Warning - this method won't work in the case the id fields are not set
        if (!(object instanceof Founder)) {
            return false;
        }
        Founder other = (Founder) object;
        if ((this.id == null && other.id != null) || (this.id != null && !this.id.equals(other.id))) {
            return false;
        }
        return true;
    }

    @Override
    public String toString() {
        return "org.ideavillage.mentormarketplace.persistence.domain.Mentor[ id=" + id + " ]";
    }
    
    public MMUser getMmuser() {
        return mmuser;
    }

    public void setMmuser(MMUser mmuser) {
        this.mmuser = mmuser;
    }

}